# Generated by Django 4.1.1 on 2022-12-11 19:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sweetapp', '0013_cart_status_orderitem_cart_ids_orderitem_invoice_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='cart_ids',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='invoice_id',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='status',
        ),
    ]
