# Generated by Django 4.1.1 on 2022-12-13 18:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sweetapp', '0014_remove_orderitem_cart_ids_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='fname',
            new_name='first_name',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='lname',
            new_name='last_name',
        ),
    ]
